### PR TITLE
Comparison App User-Friendly Error Message

### LINKED ISSUE #56: Validation: unclear error if `ac` element missing
If no element has the `ac` attribute, the error shown in the UI is

`Error: Protocol error (DOM.describeNode): Could not find node with given id`

I think this will be the most common user error (I've made it at least twice!) so a more friendly error message would be useful

### PR DESCRIPTION
**Pull request by OisinNolan**
Closes #56 

Updated HTML Snippet Comparison Error message to reflect common 'ac attribute is missing' error.

Before:
image

After:
image

### CODE REVIEW

File: validation/src/static/scripts/index.ts [hunk 1]
```diff
@@ -75,8 +75,8 @@ const getSnippetComparison = async () => {
     }
     await displayPreview();
   } else {
-    const error = await rawResponse.json();
-    resultsContainer.innerHTML = `<div class="redtext comparisonResultText">Error: ${error.message}</div>`;
+    resultsContainer.innerHTML =
+      "<div class=\"redtext comparisonResultText\">An error occurred. Make sure to mark your target element with an 'ac' attribute if you haven't! e.g. &lt;div ac&gt;Hello world&lt;/div&gt;. See console for more detail.</div>";
```
Comment (AlexLloyd0) [inline validation/src/static/scripts/index.ts:79]: Please update error thrown as discussed today :)

**Review by AlexLloyd0 — CHANGES_REQUESTED** [review]

**Review by AlexLloyd0 — APPROVED** [review]
